-- -----------------------------------------------------
-- Table `VehiAlpes`.`TIPO_TRANSPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VehiAlpes`.`TIPO_TRANSPORTE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `VehiAlpes`.`TIPO_TRANSPORTE` (
  `ID_TIPO_TRANSPORTE` INT NOT NULL ,
  `DESCRIPCION` VARCHAR(30) NOT NULL ,
  PRIMARY KEY (`ID_TIPO_TRANSPORTE`) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Modificaciones a la tabla de citas para adicionar los transportes.
-- -----------------------------------------------------
ALTER TABLE ORDEN_SERVICIO ADD COLUMN ID_TRANSPORTE_RECIBO INT NOT NULL;
ALTER TABLE ORDEN_SERVICIO ADD COLUMN ID_TRANSPORTE_ENTREGA INT NOT NULL;

ALTER TABLE ORDEN_SERVICIO ADD CONSTRAINT FK_TRANSPORTE_RECIBO 
FOREIGN KEY (ID_TRANSPORTE_RECIBO) REFERENCES VehiAlpes.TIPO_TRANSPORTE(ID_TIPO_TRANSPORTE);

ALTER TABLE ORDEN_SERVICIO ADD CONSTRAINT FK_TRANSPORTE_ENTREGA 
FOREIGN KEY (ID_TRANSPORTE_ENTREGA) REFERENCES VehiAlpes.TIPO_TRANSPORTE(ID_TIPO_TRANSPORTE);